"""initial schema

Revision ID: 5210a2308efa
Revises: 
Create Date: 2025-11-09 17:17:07.739675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5210a2308efa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact', 'CustomerID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'contact', 'phone', ['phone_number'], ['phone_number'])
    op.alter_column('fsm_state', 'statename',
               existing_type=sa.CHAR(length=30),
               type_=sa.String(length=30),
               nullable=False)
    op.alter_column('fsm_state', 'was_interested',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_foreign_key(None, 'fsm_state', 'phone', ['phone_number'], ['phone_number'])
    op.alter_column('message', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.drop_constraint(op.f('test_case_run_id_fkey'), 'test_case', type_='foreignkey')
    op.create_foreign_key(None, 'test_case', 'test_run', ['run_id'], ['run_id'])
    op.alter_column('twilio_message', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('usage', 'twilio_sid',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('usage', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usage', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('usage', 'twilio_sid',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('twilio_message', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.drop_constraint(None, 'test_case', type_='foreignkey')
    op.create_foreign_key(op.f('test_case_run_id_fkey'), 'test_case', 'test_run', ['run_id'], ['run_id'], ondelete='CASCADE')
    op.alter_column('message', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.drop_constraint(None, 'fsm_state', type_='foreignkey')
    op.alter_column('fsm_state', 'was_interested',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('fsm_state', 'statename',
               existing_type=sa.String(length=30),
               type_=sa.CHAR(length=30),
               nullable=True)
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.alter_column('contact', 'CustomerID',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
